from aiogram.types import InputMediaPhoto
markings_1 = "<b>СРОК ГОДНОСТИ И УСЛОВИЯ ХРАНЕНИЯ\n\n📦 Открытая баночка с цифрами (PAO — Period After Opening)</b>\nЧто означает: Продукт можно использовать <b>определённое время после вскрытия.</b>\nПример: «12M» — 12 месяцев после открытия.\n\n<b>⏳ Песочные часы с датой</b>\nЧто означает: <b>Минимальный срок годности</b>. После указанной даты качество может ухудшаться.\n\n<b>📖 Рука на открытой книге</b>\nЧто означает: В продукте есть <b>дополнительная информация</b>. Например, состав, рекомендации по применению или предупреждения.\n\n<b>℮ Estimated Sign</b>\nЧто означает: Обозначает, <b>что указанный объем или вес продукта соответствует стандартам ЕС.</b>"
markings_2 = "<b>КАК ПРОВЕРИТЬ СОСТАВ КОСМЕТИКИ\n\n🔎 Читайте список INCI</b> — он показывает ингредиенты от наибольшего к наименьшему количеству.\n\n🤖 <b>Используйте Avocado Bot AI</b> — просто загрузите фото состава, и он расшифрует, что внутри!\n\n🎯 Смотрите на знаки — сертификация, переработка, этичность.\n\n💚 <b>Выбирайте осознанно</b> — и ваша кожа, и планета скажут вам спасибо!\n\n✨ <b>Теперь вы знаете, как читать упаковку косметики! Делитесь гайдом и помогайте другим делать осознанные покупки!✨</b>"
markings_3 = "<b>ЭКОЛОГИЧЕСКИЕ И ЭТИЧЕСКИЕ ЗНАКИ</b>\n\n♻ <b>Петля Мёбиуса</b>\nЧто означает: Упаковка <b>подлежит переработке</b>. Иногда внутри указана цифра — процент переработанного материала.\n\n♻ <b>Треугольник с цифрой и буквами </b>\nЧто означает: <b>Тип пластика</b> и его пригодность к переработке.\n\n<b>Виды пластика и их переработка</b>\n\n- 1 <b>PET</b> (Полиэтилентерефталат) — легко перерабатывается (бутылки, контейнеры).\n- 2 <b>HDPE</b> (Полиэтилен высокой плотности) — безопасен и хорошо перерабатывается (канистры, бутылки).\n- 3 <b>PVC</b> (Поливинилхлорид) — сложно перерабатывается, содержит токсичные соединения.\n- 4 <b>LDPE</b> (Полиэтилен низкой плотности) — перерабатывается, но не везде (пакеты, обертки).\n- 5 <b>PP</b> (Полипропилен) — перерабатывается, но сложнее, чем PET (контейнеры, крышки).\n- 6 <b>PS</b> (Полистирол) — почти не перерабатывается (одноразовая посуда, пенопласт).\n- 7 <b>OTHER</b> (Другие виды пластика) — сложно перерабатывается, иногда токсичен.\n\n<b>Как правильно сдавать пластик в переработку?</b>\n\n1. <b>Промойте упаковку</b> — загрязнённый пластик не примут.\n2. <b>Разделяйте по типу</b> — крышки отдельно, PET отдельно.\n3. <b>Проверьте пункт приёма</b> — не все виды пластика принимают везде.\n\n🌍 <b>Зелёная точка</b>\nЧто означает: Производитель финансирует переработку отходов. <b>Но это не значит, что упаковка сделана из переработанных материалов!</b>\n\n🐰 <b>Кролик (Cruelty-Free, Leaping Bunny)</b>\nЧто означает: <b>Продукт не тестировался на животных.</b>\n\n🌱 <b>Vegan</b>\nЧто означает: <b>В составе нет ингредиентов животного происхождения.</b>"
markings_4 = "<b>КАЧЕСТВО И СЕРТИФИКАЦИЯ</b>\n\n✅ <b>EAC (Eurasian Conformity) </b>\nЧто означает: Продукт <b>соответствует стандартам Таможенного союза</b> (Россия, Казахстан и др.).\n\n🇪🇺 <b>CE (Conformité Européenne)</b>\nЧто означает: Соответствие <b>стандартам ЕС.  Гарантирует безопасность</b>, но не натуральность!\n\n🌿 <b>ECOCERT, COSMOS ORGANIC / NATURAL</b>\nЧто означает: <b>Продукт сертифицирован как натуральный или органический.\n\n🌍 Fair Trade</b>\nЧто означает: <b>Этичное производство</b>, без эксплуатации рабочих."
markings_5 = "НЕ НАШЕЛ СООТВЕТСТВИЯ В ФАЙЛЕ"
markings_6 = "placeholder_text"
markings_mg_1 = [
        InputMediaPhoto(media="AgACAgIAAxkBAAIYxWgAATZTtutyNeuAyqQoIIlIYxT4agACOe4xGzFqAUiH0OvBH4-oOAEAAwIAA3kAAzYE", caption="Что означают ключевые показатели по срокам годности?  📅"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIYyWgAATZs07-W8RbEJFnBr1jcK0oR1gACOu4xGzFqAUgbiDTxOyHWiAEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIYzWgAATZ4URpEJpBpeaPgGEojTnvLvAACO-4xGzFqAUiSbXYqAAEbLngBAAMCAAN5AAM2BA"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIY0WgAATaDS_z5WHh2VzUotIJkycf0kgACPO4xGzFqAUjJslFN6CqfuwEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIY02gAATaOW2SYJSy6MulGd04wQP3nzAACPe4xGzFqAUg12fmKs0VA_AEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIY22gAATahNNKpqeh_VSDeQrgg2Eb0bAACPu4xGzFqAUh0d5fthTgUdQEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIY32gAATarPUzLLo45HfhLOMXyBuEWGgACP-4xGzFqAUiD2FBBBFNQoAEAAwIAA3kAAzYE"),
        ]
markings_mg_2 = [
        InputMediaPhoto(media="AgACAgIAAxkBAAIYtWgAATXKeBSK41ugs70qYMp0ZSJNqgACNO4xGzFqAUj2y89bE3TroAEAAwIAA3kAAzYE", caption="Тут про ключевые знаки, виды пластика и как правильно сдавать тару в переработку ♻️"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIYuWgAATXQ-hE5AmhTNAkKv9_rj9aF5QACNe4xGzFqAUiPzqDM57sR4QEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIYvWgAATXW686m8Ar95xvUZH4ltZUTrwACNu4xGzFqAUjJU--tnzQ_YwEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIYwWgAATXbePqwPtA7P3meTAy0whJSiAACN-4xGzFqAUiPEGu3-Cc8twEAAwIAA3kAAzYE")
        ]
markings_mg_3 = [
        InputMediaPhoto(media="AgACAgIAAxkBAAIY42gAATbYA0gkG7-4Mam3MwUQ0c6N0gACQe4xGzFqAUgnOWFa1sv80gEAAwIAA3kAAzYE", caption="Что означают ключевые показатели по утилизации и безопасности? 👇"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIY52gAATbndgH49ye5PJ9q23UPNBAhUgACQu4xGzFqAUgzykC3t3LsRAEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIY62gAATbwVtnkzbpwGc7rg5G5EOjhOwACQ-4xGzFqAUj4lEd6Z4kI-QEAAwIAA3kAAzYE"),
        ]
markings_mg_4 = [
        InputMediaPhoto(media="AgACAgIAAxkBAAIY72gAATcczMFIaKMAAYTFw54bvqUsw1cAAkTuMRsxagFIYXo-xGP2IwgBAAMCAAN5AAM2BA", caption="Качество и сертификация, как это отследить? 👇"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIY82gAATdS14_nLTRSiMCGRdMrUatQNAACRe4xGzFqAUhD-d67yl206QEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIY92gAATdZFWLCSSa7z4VmI_HLImoHEAACRu4xGzFqAUgT4_4xCB2fEQEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIY-2gAATdgeCPEKoUd_RSfMDovsL7c6AACR-4xGzFqAUh0Qg7A0uhXnAEAAwIAA3kAAzYE"),
        ]
markings_mg_5 = [
        InputMediaPhoto(media="AgACAgIAAxkBAAIY_2gAATeIChnU59WnAZSB9Exg50nAlwACSO4xGzFqAUgBB1V_TrufpAEAAwIAA3kAAzYE", caption="Что означают разноцветные полоски на тубах? 😇"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZA2gAATeMLacqFk8brlsmE5LzpWSKmQACSe4xGzFqAUgNbxsYRw_dqAEAAwIAA3kAAzYE"),
        ]
markings_mg_6 = [
        InputMediaPhoto(media="AgACAgIAAxkBAAIZB2gAATefH6A_DBITYclkoQX7beuAugACSu4xGzFqAUi76q16H46PegEAAwIAA3kAAzYE", caption="Для особо внимательных. Чек-лист по проверке косметики 😇"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZC2gAATelaONX2fSwXtqKZGfdsFbjogACS-4xGzFqAUgkG4vSesULZwEAAwIAA3kAAzYE"),
        ]

avo_box_text_long_2 ="1) 🦷 LiMa, Минеральная зубная паста с мятой и кокосом \n📦 75 мл \n💰 825₽ \n🎟 Промокод: MINT \n🔗 <a href=\'https://limatooth.ru/\'>Перейти на сайт</a>\n🌿 Без фтора, SLS и химии. Мягко очищает, укрепляет десны. Подходит для всей семьи и освежает дыхание надолго\n\n\n2)🛁 Море дома, Морская соль для ванн «Релакс» с эфирными маслами\n 📦 1 кг\n 💰 590₽\n 🎟 Промокод: RELAX50\n 🔗 <a href=\'https://more-doma.ru/product/relaks-s-efirnymi-maslami-seriya-%E2%84%966/\'>Перейти на сайт</a>\n🌿 Расслабляет тело и ум, снимает напряжение, помогает восстановиться после стрессов и перегрузок\n\n\n3)👁️ Everyday For Future, Тушь «Удлинение» с экстрактом авокадо\n 📦 10 мл\n 💰 1293₽\n 🎟 Промокод: EFF50\n 🔗 <a href=\'https://vimnaturae.ru/catalog/makiyazh/3940/?ysclid=m8iream5zu585706511\'>Перейти на сайт</a>\n🌿 Веганская формула с маслами и ячменной водой. Питает, удлиняе\n\n\n4)💅 Vimbio, Набор для маникюра «Укрепление и уход»\n 📦 50 мл\n 💰 2300₽\n 🎟 Промокод: VIMBIO50\n 🔗 <a href=\'https://vimnaturae.ru/catalog/manikyur/4631/\'>Перейти на сайт</a>\n🌿 11-Free формула, витамины и водоросли. Укрепляет и восстанавливает ногти в 2 этапа. Безопасно и эффективно в домашних условиях.\n\n\n5)🍍 Feel Nature, Фруктовая энзимная маска\n 📦 50 мл\n 💰 1976₽\n 🎟 Промокод: FEEL50\n 🔗 <a href=\'https://feelnature.ru/shop/lizo/fruktovaja-jenzimnaja-maska-2/?ysclid=m8iraw7z2p17529505\'>Перейти на сайт</a>\n🌿 Щадящий энзимный пилинг. Очищает, сужает поры, борется с пигментацией и акне. Подходит даже для чувствительной кожи.\n\n\n6) 🧴 Sibirbotaniq, Увлажняющий флюид для тела\n 📦 200 мл\n 💰 1800₽\n 🎟 Промокод: FLUID50\n 🔗 <a href=\'https://sibirbotaniq.com/catalog/dlya-tela/flyuidy-i-krema/\'>Перейти на сайт</a>\n🌿 Легкая текстура, глубокое увлажнение и питание. С аллантоином и пантенолом — для мягкой, бархатистой кожи.  \n💐 В 3 ароматах: родиола + гранат (цитрусово-мускусный), хлопок + гинкго (цветочно-пряный) и мальва + календула (фруктово-жасминовый)\n\n\n7) 💋 Eco Make, Оттеночный бальзам для губ 2в1\n 📦 2,5 г\n 💰 670₽\n 🎟 Промокод: ECOMAKELIPS\n 🔗 <a href=\'https://ecomake.ru/catalog/ottenochnyy-balzam-dlya-gub-2v1/\'>Перейти на сайт</a>\n🌿 Увлажняет, питает и заживляет. Без липкости, с натуральными маслами и витамином Е.\n 🎨 В 3 оттенках: Карамельный янтарь, Малиновый кварц, Вишнёвый аметист\n\n8) ✨ Angel Lab, Флюид «Деликатный»\n 📦 30 мл\n 💰 3360₽\n 🎟 Промокод: ANGEL50\n 🔗 <a href=\'https://angellab.pro/catalog/flyuid-delikatnyj\'>Перейти на сайт</a>\n🌿 Питает, увлажняет и восстанавливает барьер кожи. Без эмульгаторов и ПАВов. Подходит даже для самой чувствительной кожи."
avo_box_text_long_3 = "9) 🫧 Yodometics, Органик вуаль для умывания «Сливочный пломбир»\n 📦 90 мл\n 💰 650₽\n 🎟 Промокод: YODO50\n 🔗 <a href=\'https://www.yodometics.ru/test/tproduct/881849107-692231496511-organik-vual-dlya-umivaniya-clivochnii-p\'>Перейти на сайт</a>\n🌿 Глубоко очищает, сужает поры, выравнивает тон и борется с воспалениями. Must-have для городской кожи.\n\n10) 🧴 True Alchemy, Флюид для умывания Calamine & Arginine\n 📦 300 мл\n 💰 850₽\n 🎟 Промокод: TRUE50\n 🔗 <a href=\'https://levrana.ru/catalog/true-alchemy/953/\'>Перейти на сайт</a> \n🌿 Успокаивает, снимает зуд и воспаления. Подходит для чувствительной кожи, бережно очищает и увлажняет.\n\n\n11) 🌿 Levrana, Двухфазная сыворотка для лица с CBD\n 📦 30 мл\n 💰 650₽\n 🎟 Промокод: AVOCADOAI\n 🔗 <a href=\'https://levrana.ru/catalog/kosmetika/dlya_litsa/lineyka_cbd/9482/\'>Перейти на сайт</a>\n🧴 Успокаивает, увлажняет и восстанавливает. Снижает воспаления и жирность. Идеальна для сухой и чувствительной кожи.\n\n\n12) 🌿 Levrana, Восстанавливающий крем для лица с CBD\n 📦 50 мл\n 💰 650₽\n 🎟 Промокод: AVOCADOAI\n 🔗 <a href=\'https://levrana.ru/catalog/kosmetika/dlya_litsa/lineyka_cbd/9483/\'>Перейти на сайт</a>\n🧴 Успокаивает, восстанавливает и увлажняет. Снимает раздражения и улучшает барьерные функции кожи. Подходит для чувствительной кожи.\n\n13) 🧂 Noni Care, Сахарный скраб для тела с АНА-кислотами\n 📦 200 мл\n 💰 1585₽\n 🎟 Промокод: AIBOX50AVO\n 🔗 <a href=\'https://naturcream.ru/catalog/nonicare/garden_of_eden/sakharnyy_skrab_dlya_tela_c_ana_kislotami_sugar_body_scrub_200ml/\'>Перейти на сайт</a>\n🌿 Мягко отшелушивает, выравнивает кожу, борется с целлюлитом. Увлажняет и делает кожу гладкой и упругой.\n\n\n14) 🍑 Kate’s Natural Care, Твердый шампунь «Спелое манго»\n 📦 70 г\n 💰 690₽\n 🎟 Промокод: AVOKATE50\n 🔗 <a href=\'https://kates-naturalcare.ru/\'>Перейти на сайт</a>\n🌿 Без сульфатов, с маслом манго и пантенолом. Питает и укрепляет тонкие волосы. Удобный, экономичный и экологичный формат.\n\n\n15) 🎨 MAOKA, Набор минеральной косметики\n 📦 6 средств в мини-формате\n 💰 1490₽\n 🎟 Промокод: MAOKA50BOT\n 🔗 <a href=\'https://maoka.ru/decorative/tproduct/794082911-682417595432-nabor-semplov-mineralnoi-kosmetiki\'>Перейти на сайт</a>\n🌿 100% минеральный состав, SPF 25–30, не забивает поры. Подходит для чувствительной кожи. Тон, румяна, бронзер, консилер и пудра — всё для естественного макияжа.\n\n16) 👛 YES-IDEYA, Фермуар яблоко\n💰 11900₽ \n🎟 Промокод: AVOBOT\n🔗 <a href=\'http://www.yes-ideya.ru/\'>Перейти на сайт</a>\n🌿  Изготовлен вручную из яблочной кожи, смесовой подкладки"    
promo_text = "<b>Ваши персональные скидки от -15 %</b> ❤️\n\n<blockquote>Не забудьте добавить промокод — тогда ваша скидка применится автоматически</blockquote>\n\n\n\n1) By sadova\n💰-15%\n🎟 Промокод: АВОКАДОБОКС \n🔗 https://sadova.co/ \n\n🌿 Бесплатная доставка при сумме заказа от 3000р по России, а также в Беларусь, Казахстан и Киргизию \n\n2) Zaharova\n💰-15%\n🎟 Промокод: AVOBOT\n🔗 https://www.zaharova.shop/\n\n\n3) TRAWA\n💰-10%\n🎟 Промокод: TRAWAAVO\n🔗 https://trawaoil.ru/\n\n\n4) Море дома\n💰-15%\n🎟 Промокод: AVBOX\n🔗 https://more-doma.ru/ \n\n🌿 Скидки на серию «Магний+», эфирные масла и экстракты."

avo_box_media_gr_1 = [
        InputMediaPhoto(media="AgACAgIAAxkBAAIZRWgAAUPHd4hxQqstYdIQpyw2rW6_0wACZ-4xGzFqAUgZy6dX3t3PBwEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZSWgAAUPSUGYHAdXQ1FuRC9lfI-8t4gACaO4xGzFqAUiQ-hykZW1MkwEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZTWgAAUPbleR0x_PS9Xtwo2DtLrc94AACae4xGzFqAUiQLa7URxS5zQEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZUWgAAUPjLiQ9qsownSnPjJfksOf6YAACau4xGzFqAUirqyKt9zqewgEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZVWgAAUPtxUQC_wSvju4gbb-KXrCf3AACa-4xGzFqAUjrntQeCS3blQEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZWWgAAUP0F5YiRieCjqaTB2rrIJg02QACbO4xGzFqAUh8gDX5NJ1VsQEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZXWgAAUP9vYlnLYV4257dGJJOuIhvBwACbe4xGzFqAUhs9PX2VsEP0wEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZYWgAAUQGLV0gbRySPjXxMfGiCrvdeQACbu4xGzFqAUj7Os0Usy2fUwEAAwIAA3kAAzYE"),
        ]

avo_box_media_gr_2 = [
        InputMediaPhoto(media="AgACAgIAAxkBAAIZZWgAAUQhMHUlbFgBpsYckta2-JGLMQACb-4xGzFqAUiQAfbor9FmxgEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZaWgAAUQsvJ8FsPFdnm2hXQABGxrDZbwAAnDuMRsxagFICDEZgndYFe8BAAMCAAN5AAM2BA"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZbWgAAUQ1mQ2C7miAi-i985ZTEpIlnAACce4xGzFqAUgvGogM77TPbgEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZcWgAAUQ-_Az3S9MYT27T59jmFnUDqQACcu4xGzFqAUjaeiiYHQVb1AEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZdWgAAURLRPuozG-fGR7dNkrT0yyjbgACc-4xGzFqAUhjD9ypzzln9QEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZeWgAAURSHSFdaQ8cg84mDrTV_0y8swACdO4xGzFqAUjfsh81pKGl8wEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZfWgAAURaqw7p8o0OHoZbLqe5HC_DGgACde4xGzFqAUhvH2F45xquWwEAAwIAA3kAAzYE"),
        InputMediaPhoto(media="AgACAgIAAxkBAAIZgWgAAURit76Z9vBlEqeaRYiyaoOSOQACdu4xGzFqAUhACO_57rlOAwEAAwIAA3kAAzYE"),
        ]
